### ISSUE TITLE
Type declaration typescript

### ISSUE THREAD

**Issue by wagnerfillio** [dmuy/Material-Toast#13]
Hi, how can I resolve this? Using the script I get this error even though toast works.

"Could not find a declaration file for module '@dmuy/toast'. 'd:/React/planner-ts/node_modules/@dmuy/toast/dist/mdtoast.js' implicitly has an 'any' type. Try `npm i --save-dev @types/dmuy__toast` if it exists or add a new declaration (.d.ts) file containing `declare module '@dmuy/toast';`"

**Comment by dmuy** [comment]
Hello @wagnerfillio,

This library is JavaScript, and TypeScript looks for type definitions for it. As I am not familiar on how to code in TypeScript, I have not made any type declaration for this library. But I've read if you `npm install --save-dev @types/node` you can normally (no errors) use any JavaScript libraries.
