### ISSUE TITLE
Minify and upload to CDN?

### ISSUE THREAD

**Issue by Aditya94A** [dmuy/Material-Toast#2]
Hey there! Thanks for making this amazing library, this is exactly what I was looking for.

* How about adding a `mdtoast.min.js` and `mdtoast.min.css` (minifying the resources)?
* Also, some devs might prefer libraries like this to be hosted on CDNs :)

**Comment by dmuy** [comment]
Hello there @AdityaAnand1,

Thank you for having an interest in my library, and yeah I planned on adding minified css and javascript files (but I totally forgot, thanks for bringing that up haha). Regarding CDNs, I'm not really sure how that works, but I've stumbled upon this: [RawGit](https://rawgit.com), apparently this **serves raw files directly from GitHub**.

**Comment by Aditya94A** [comment]
Yup, that'd be great :)

**Comment by MartinKolarik** [comment]
You can use [jsDelivr CDN](https://www.jsdelivr.com/features#gh), the only thing you'd need to do is tag versions here on GitHub. It can also take care of minifying the files if needed.

**Comment by dmuy** [comment]
Wow, that's very useful @MartinKolarik 😄 thanks!
