### ISSUE TITLE
if multiple toasts --> it only displays the last one

### ISSUE THREAD

**Issue by SidneyMachara** [dmuy/Material-Toast#3]
// Initializes default toast with duration of 10 seconds (this will not show the toast since init is set to true)
  var myToast = mdtoast('This is a toast message.', { duration: 1000, init: true });
  var myToast2 = mdtoast('This is a .', { duration: 1000, init: true });

  // Displays the toast
  myToast.show();
  myToast2.show(); <-- only this will display

**Comment by dmuy** [comment]
Hi @SidneyMachara,

Yes, it is designed that way. It's not the same as other libraries which stacks up notifications/messages.

**Comment by femto-code** [comment]
Hi @dmuy !
Thank you for your awesome work, I like your toast library.
Is there a way to have the notifications appear one after another?
EDIT: I found my own solution by writing a wrapper function to stack the notifications.

**Comment by mlturner88** [comment]
> Hi @dmuy !
> Thank you for your awesome work, I like your toast library.
> Is there a way to have the notifications appear one after another?
> EDIT: I found my own solution by writing a wrapper function to stack the notifications.

Would you mind sharing a gist of your solution?

**Comment by femto-code** [comment]
> > Hi @dmuy !
> > Thank you for your awesome work, I like your toast library.
> > Is there a way to have the notifications appear one after another?
> > EDIT: I found my own solution by writing a wrapper function to stack the notifications.
> 
> Would you mind sharing a gist of your solution?

Yes, I'd be glad to do so! Give me just 2-3 days, until I have a little more time. I'll post the link in this thread!

**Comment by femto-code** [comment]
> > Hi @dmuy !
> > Thank you for your awesome work, I like your toast library.
> > Is there a way to have the notifications appear one after another?
> > EDIT: I found my own solution by writing a wrapper function to stack the notifications.
> 
> Would you mind sharing a gist of your solution?

Sorry for the delay - I will post the link in the next few days.

**Comment by femto-code** [comment]
Sorry again for the delay. Now I've got time. Do you still need the stacking of notifications @mlturner88 ?

**Comment by mlturner88** [comment]
> Sorry again for the delay. Now I've got time. Do you still need the stacking of notifications @mlturner88 ?

No, but I appreciate you following up with me! I ended up using another library.
